### ISSUE TITLE
goth UX: reduce the number of tracebacks in logs

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1530] opened 2021-07-21 09:18 UTC
Improve internal error propagation to reduce the number of tracebacks in logs (e.g. when trying to manually handle errors).

Consult with the goth team whether it's already WIP

**Comment by zakaprov** [comment] 2021-07-22 10:20
This is in progress here: https://github.com/golemfactory/goth/issues/517

**Comment by tworec** [comment] 2021-07-22 10:21
Closing as a duplicate of the above.

**Closed by tworec** 2021-07-22 10:21 UTC
