### ISSUE TITLE
Certificate revocation handling through CRL or OCSP

### ISSUE THREAD

**Issue by jalas167** [golemfactory/yagna#2093] opened 2022-07-20 08:39 UTC
OpenSSL can handle certificates revocation through calling hosted CRL file or OCSP service.
We will most likely need to host CRL file or expose OCSP service and access one of them from ya-provider.

**Comment by pwalski** [comment] 2022-08-03 10:34
Missing feature allowing to read CRL from file waits to be merged to rust `openssl` lib https://github.com/sfackler/rust-openssl/pull/1123
The problem is CRLs usually have short expiration date, so providers should be able to handle certificate property named `crlDistributionPoints` https://jamielinux.com/docs/openssl-certificate-authority/certificate-revocation-lists.html#prepare-the-configuration-file

**Comment by evik42** [comment] 2023-03-01 10:34
Not relevant anymore. Closing in favor of #2156

**Closed by evik42** 2023-03-01 10:34 UTC
Labels: out-network
