### ISSUE TITLE
galatea task hangs on second run command call

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1364] opened 2021-05-26 14:10 UTC
Repos:
https://github.com/golemfactory/galatea/blob/pnowosie/pass-requests-to-classificators-APPS-83/provider/test/yagna_batch_test.py

https://github.com/golemfactory/galatea/blob/pnowosie/pass-requests-to-classificators-APPS-83/provider/classifier/classifier.py

Image hash: c6b743459d3428fb860582e556ceba1c76dbc8a1d599a55dcf73e437

**Comment by Wiezzel** [comment] 2021-05-26 14:32
This error occurs with provider in version `v0.6.7-beta.1` but does not occur when provider is in version `v0.6.5`.

**Comment by mfranciszkiewicz** [comment] 2021-05-31 11:23
https://github.com/golemfactory/ya-runtime-sdk/pull/11 should fix this issue

**Comment by Wiezzel** [comment] 2021-05-31 11:34
> [golemfactory/ya-runtime-sdk#11](https://github.com/golemfactory/ya-runtime-sdk/pull/11) should fix this issue

:crossed_fingers:

**Comment by mfranciszkiewicz** [comment] 2021-05-31 12:39
> ~[golemfactory/ya-runtime-sdk#11](https://github.com/golemfactory/ya-runtime-sdk/pull/11) should fix this issue~

This issue most probably needs to be fixed on the Supervisor level

**Comment by nieznanysprawiciel** [comment] 2021-05-31 17:01
The problem is first run command, that runs in the background. Execution finishes immediately after spawning process, so ExeUnit stops tracking this process, but output is still generated and Supervisor doesn't consume output events from the queue. The second spawned process finishes correctly, but event about this finish is stacked in the queue and never reaches Supervisor.

I'm working on fix on Supervisor level

**Comment by Wiezzel** [comment] 2021-06-01 07:17
@nieznanysprawiciel Let me know if you find some way to handle this in supervisor.

**Comment by mfranciszkiewicz** [comment] 2021-06-02 12:24
@Wiezzel `galatea` test is passing successfully with ExeUnit built from https://github.com/golemfactory/yagna/pull/1384. Could you confirm that the issue is resolved?

**Comment by mfranciszkiewicz** [comment] 2021-06-07 13:57
Resolved by #1384

**Closed by mfranciszkiewicz** 2021-06-07 13:57 UTC
Labels: apps-dispatch, beta.2.patch.1, galatea
