### ISSUE TITLE
Daemon stuck on testing session

### ISSUE THREAD

**Issue by maaktweluit** [golemfactory/yagna#1141] opened 2021-03-10 13:46 UTC
On today's testing session ALL requestors stopped computing tasks.

We need to investigate how this happened and fix it.

Notable glitches during the session:
- Zksync Rinkeby was down ( 502 errors ) Seems handled properly
- Node resolver parsing error

Both seem to recover properly, attachin ALL requestor data-dirs to help the investigation

GJ: 
[GolemFactory.yagna.zip](https://github.com/golemfactory/yagna/files/6116248/GolemFactory.yagna.zip)
Mateusz:
[data.zip](https://github.com/golemfactory/yagna/files/6116257/data.zip)
Philip:
[Arkiv.zip](https://github.com/golemfactory/yagna/files/6116264/Arkiv.zip)
Adam:
[yagna.tar.gz](https://github.com/golemfactory/yagna/files/6116277/yagna.tar.gz)
blue:
[GolemFactory.yagna-20210310.tar.gz](https://github.com/golemfactory/yagna/files/6122317/GolemFactory.yagna-20210310.tar.gz)

**Comment by mateuszsrebrny** [comment] 2021-03-22 10:37
@Wiezzel @maaktweluit how is this doing? should we close this as it is not reproducible and there are not leads on how to analyze this further?

**Comment by Wiezzel** [comment] 2021-03-22 13:12
@mateuszsrebrny I've established that server errors from zkSync operator are handled properly and do not cause panic in yagna daemon. That finished my task I guess.

**Comment by mateuszsrebrny** [comment] 2021-03-30 06:53
@Wiezzel so what do you propose should happen with this issue? somebody else should have a look? or we should won't fix it as there is no leads? or maybe we should try reproducing? or maybe reproducing doesn't seem to promising and we still should won't fix it?

**Comment by Wiezzel** [comment] 2021-03-30 08:55
@mateuszsrebrny Unless someone else volunteers to work on this, I'd close it as 'can't reproduce'.

**Closed** 2021-03-30 09:27 UTC
Labels: beta.2, wontfix
