### ISSUE TITLE
[Heisenbug] Ageements wo activity (not accepting tasks by network)

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1074] opened 2021-02-24 09:22 UTC

**Comment by tworec** [comment] 2021-02-25 12:31
Logfile from @ederenn (below) shows that the yagna network (`devnet-beta.1`) after being unresponsive (quite long -- 15-45min) has recovered itself before 60min. Recovery was when all other test sess participants left the session and probably killed their requestors. Magda was most patient! :)

[2021-02-23_ederenn_yapapi_zksync_glmsync.txt](https://github.com/golemfactory/yagna/files/6042899/2021-02-23_ederenn_yapapi_zksync_glmsync.txt)

It is known that @zakaprov @mbenke @rad9k have also troubles with unresponding network (no offers), but we do not have logs from them.

At today's (2021-02-25) test sess, we (@mfranciszkiewicz @jiivan @etam @mateuszsrebrny @ederenn @nieznanysprawiciel and @tworec ) were not able to reproduce this network lag. We were using all three OS and both yapapi and yajsapi. Everything went well. So I'm closing.

**Comment by etam** [comment] 2021-02-26 15:33
Yagna 0.6.0, subnet community.4

[qbam.4.log.gz](https://github.com/golemfactory/yagna/files/6050636/qbam.4.log.gz)

At 14:46 UTC a computation was finished, but then it was rejecting proposals saying "No capacity available. Reached Agreements limit: 1" until 15:13 when agreement expired.

**Comment by cryptobench** [comment] 2021-02-26 16:22
[yajsapi-current.log](https://github.com/golemfactory/yagna/files/6050943/yajsapi-current.log)
[datadir.zip](https://github.com/golemfactory/yagna/files/6050944/datadir.zip)

My requestor logs from when it happened today.

**Comment by jiivan** [comment] 2021-03-01 16:05
The issue is correctly summarized by @etam comment:

> At 14:46 UTC a computation was finished, but then it was rejecting proposals saying "No capacity available. Reached Agreements limit: 1" until 15:13 when agreement expired.

Looks like same thing happened in @cryptobench (but we have requestor logs), also timestamps are similar which suggests that they were aftermath of same/similar event that took place near 14-15. There were agreements with properly finished activities, but without proper *TerminateAgreement*, thus providers were effectively disabled till agreements timed out (timeout set by requestor and stored in agreement).

**Comment by shadeofblue** [comment] 2021-03-02 14:00
@jiivan shouldn't the DebitNote mechanism - and thus lack of the keep-alive responses - step in here and kill those activities anyway before the task times out?

**Comment by tworec** [comment] 2021-03-03 10:21
will be resolved by #1108

**Comment by tworec** [comment] 2021-03-19 09:31
closed via #1108

**Closed** 2021-03-19 09:35 UTC
Labels: beta.1.patch, bug, m-market
