### ISSUE TITLE
`unknown stream recipient` as GSB address

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#2211] opened 2022-09-13 15:15 UTC
```
[2022-09-13T12:37:58.773+0200 ERROR ya_activity::error] Activity API server error: GSB error: Bad request: GSB failure: Called service `unknown stream recipient` is unavailable
```

https://www.notion.so/golemnetwork/requestor-testing-session-hybrid-net-6-d3fe24df7e3247fbacdc23dff058c27c#55a61f8164814a1ea17dee6e086d3f71

Impact: low
Severity: weird

**Comment by wkargul** [comment] 2022-10-11 10:34
Bug can not be reproduced. Due to weak log context we are not able to find out what was the real issue here.

Log context has been fixed with more descriptive one -> https://github.com/golemfactory/ya-service-bus/commit/d1a6dcb9469e2d69be0e346f7b585ebb7e882d0a

**Closed by wkargul** 2022-10-11 10:34 UTC
Labels: bug
