### ISSUE TITLE
Error accepting connection: No file descriptors available (os error 24

### ISSUE THREAD

**Issue by jiivan** [golemfactory/yagna#2253] opened 2022-10-12 08:33 UTC
When running a significant task (i.e. secondary benchmarker), yagna deamon runs out of file descriptors & finally freezes. There is a significant delay between first log about no file descriptors and daemon freezing.

First information about problem:
`[2022-10-08T13:52:07.116+0000 ERROR actix_server::accept] Error accepting connection: No file descriptors available (os error 24)`

Last log entry before restart a few day later:
`[2022-10-08T23:59:59.660+0000 ERROR actix_server::accept] Error accepting connection: No file descriptors available (os error 24)`

Maybe this situation could be handled in more friendly way for the user.
[yagna_r2022-10-11_11-14-02.log.gz](https://github.com/golemfactory/yagna/files/9763122/yagna_r2022-10-11_11-14-02.log.gz)

**Comment by nieznanysprawiciel** [comment] 2023-01-17 17:39
Closing as duplicate of: https://github.com/golemfactory/yagna-triage/issues/232

**Closed by nieznanysprawiciel** 2023-01-17 17:39 UTC
