### ISSUE TITLE
agreement for activity not found

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/yagna#1383] opened 2021-06-01 12:16 UTC
Is it a big problem?

```
[2021-06-01T12:45:15.574+0200 DEBUG ya_service_bus::typed] Call to SendInvoice failed: Service error: External service error: Activity service error: Service error: DAO error: Not found: agreement id for activity: ec25ce0e3d5e45739ce571f2cf5784e1
```
[GolemFactory.yagna (1).zip](https://github.com/golemfactory/yagna/files/6576137/GolemFactory.yagna.1.zip)

**Comment by nieznanysprawiciel** [comment] 2021-06-01 13:55
It is known bug. Issue for this: https://github.com/golemfactory/yagna/issues/1162

**Comment by tworec** [comment] 2021-06-01 14:43
closing as a duplicate of #1162

**Closed by tworec** 2021-06-01 14:43 UTC
Labels: beta.2, core-payment, impact: high, severity: minor
