### ISSUE TITLE
Return a proper (cmd not implemented) message for `yagna id drop`

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/yagna#1535] opened 2021-07-21 10:53 UTC
Currently yagna id drop method is not implemented and return and error. 

**Acceptance Criteria:**
- Add a more user friendly error message for yagna id drop - example "This method is not yet implemented".

**Additional Information:**
- Task for implementing yagna id drop: https://github.com/golemfactory/yagna/issues/455

**Comment by jiivan** [comment] 2022-10-12 07:42
It's a duplicate of #455

**Comment by evik42** [comment] 2022-11-09 15:03
@jiivan this issue is about returning a more user friendly error message without implementing the logic.
#455 is about actually implementing `yagna id drop`.

**Comment by pwalski** [comment] 2023-02-28 17:53
Moving to maintenance because message `Error: Bad request: endpoint address not found` on `id drop` of existing address is a bug.

**Comment by jalas167** [comment] 2024-02-29 08:12
closing as yagna id drop is already implemented in https://github.com/golemfactory/yagna/issues/455

**Closed by jalas167** 2024-02-29 08:12 UTC
