### ISSUE TITLE
Large stdout is corrupted

### ISSUE THREAD

**Issue by pgrzy-golem** [golemfactory/yagna#2879] opened 2023-11-03 07:41 UTC
When capturing large stdout (1MB+), the output is corrupted. It is missing last ~64kb of data. 

The amount of missing data for the same input is always the same (at least for about 5 tests I did).

The function used to get the result: /activity/{activityId}/exec/{batchId} (application/json version, eventsource version wasn't tested)

**Comment by evik42** [comment] 2023-11-06 17:59
Duplicate of #2478

**Closed by evik42** 2023-11-06 17:59 UTC
Labels: bug
