### ISSUE TITLE
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done

### ISSUE THREAD

**Issue by Danhkaka** [golemfactory/yagna#1777] opened 2021-12-22 14:35 UTC
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__The funding of 11999.9815 GLM (6651.02 USD @ $0.55/GLM)  attached to this issue has been approved & issued to @controlcpluscontrolv.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/golemfactory/yagna/1456/100026046)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $5,152,906.81 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

_Originally posted by @gitcoinbot in https://github.com/golemfactory/yagna/issues/1456#issuecomment-937914707_

**Comment by mat7ias** [comment] 2021-12-23 11:38
Closing, duplicate of [this comment](https://github.com/golemfactory/yagna/issues/1456#issuecomment-937914707). Must be a mistake.

@Danhkaka Please recreate the issue if you have one related to Yagna.

**Closed by mat7ias** 2021-12-23 11:38 UTC
