### ISSUE TITLE
zkSync transaction verification failure: Nonce mismatch

### ISSUE THREAD

**Issue by tworec** [golemfactory/yagna#1311] opened 2021-05-11 12:08 UTC
Yagna version: `0.6.5 (6317bb3d 2021-05-06 build #141)`.
During GolemLife invocation we've encountered 

```
[2021-05-07T10:27:44Z ERROR ya_zksync_driver::driver] ZkSync transaction verification failed. tx_details=TransactionEntity { tx_id: "1a0600cb-af53-4590-a5a8-26d3e476c480", sender: "0xa96d3f3e177687fb0b5f990d5c4000923b49430b", nonce: "", timestamp: 2021-05-07T10:27:31.656396012, status: 2, tx_type: 0, encoded: "", signature: "", tx_hash: Some("99b55ffdc9cd005f20e611f038351e27bc690cbc296a44857b3d6752ff88e493") } error=Nonce mismatch
```

Tx was rejected by zkSync
https://zkscan.io/explorer/transactions/968368e5e8dda7bebaf312d8996d9d231083992a58e0e034d8a8f0c4da0931fd

[yagna_r2021-05-07_08-54-06.restart-0000.log.gz](https://github.com/golemfactory/yagna/files/6458985/yagna_r2021-05-07_08-54-06.restart-0000.log.gz)

**Comment by mateuszsrebrny** [comment] 2021-06-16 13:44
The issue is old, it happens rarely. 
We should spend 3 mins to make sure that we can close it :)

**Comment by mbenke** [comment] 2021-07-14 08:58
Got it again yesterday:

```
[2021-07-13T18:29:26.369+0200 INFO  ya_zksync_driver::zksync::wallet] Created zksync transaction with hash=417c0e4081900576ac65b26deb99e3318276e7e714b3b0aa546a3521dc86b6ee  
[2021-07-13T18:29:28.694+0200 INFO  ya_zksync_driver::zksync::wallet] Created zksync transaction with hash=aa1ff73b17114e20f7036b1acc89c813371fb825e42de516534d0b6958e57172 
[2021-07-13T18:29:31.905+0200 ERROR ya_zksync_driver::driver] ZkSync transaction verification failed. tx_details=TransactionEntity { tx_id: "c1bd09a8-ef3e-4efa-9629-049a7e534418", sender: "0xa96d3f3e177687fb0b5f990d5c4000923b49430b", nonce: "", timestamp: 2021-07-13T16:29:28.695055389, status: 2, tx_type: 1, encoded: "", signature: "", tx_hash: Some("aa1ff73b17114e20f7036b1acc89c813371fb825e42de516534d0b6958e57172"), network: Mainnet } error=Nonce mismatch
```

Indeed the two transactions seem to atttempt to use the same nonce:

https://zkscan.io/explorer/transactions/417c0e4081900576ac65b26deb99e3318276e7e714b3b0aa546a3521dc86b6ee
https://zkscan.io/explorer/transactions/aa1ff73b17114e20f7036b1acc89c813371fb825e42de516534d0b6958e57172

**Comment by maaktweluit** [comment] 2021-07-14 09:00
That is strange, then both the database and the zksync API pass along the wrong nonce.. might be a race condition somewhere..

We have planning today so i will raise this :)

**Comment by maaktweluit** [comment] 2021-07-28 13:20
After investigation we found that this is not stored in the database because zksync (usually) replies a valid nonce in time.

We discussed this inside the team and we do not want to store the nonces in database ( too much work for too little benefit )

We want do to improve the flow to check for nonce errors and make sure this transaction get re-sent.

```
if 'nonce' in error
    payment.status = not sent
else
    payment.status = failed
```

**Closed** 2021-08-30 09:06 UTC
Labels: bug, m-payment, severity: minor, impact: low, optional, beta.3
