### ISSUE TITLE
Failed to save Offer - expired. investigate

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1087] opened 2021-02-25 14:53 UTC
```
[2021-05-24T17:13:31Z WARN  ya_market::matcher::handlers] Failed to save Offer [618609ab0f074041adcd0ca383c471a1-a1c634796e24bf525baa12a69ff5f630d5d7c183b16e3f30501f2ceb6601941d]. Error: Offer [618609ab0f074041adcd0ca383c471a1-a1c634796e24bf525baa12a69ff5f630d5d7c183b16e3f30501f2ceb6601941d] expired.
```

What:
- [x] Decrease log level (done via #1367)
- [ ] Investigate why Nodes are sending expired Offers

**Comment by scx1332** [comment] 2021-05-27 09:08
Log level decreased. Investigate part is left open.

**Comment by maaktweluit** [comment] 2021-05-31 12:55
I have looked into the possible reasons for sending a expired offer and found this:
https://github.com/golemfactory/yagna/blob/master/core/market/src/db/dao/offer.rs#L74

I think it should not filter the unsubscribes by timestamp, all un-subscribes should be removed from the list.

**Comment by maaktweluit** [comment] 2021-06-07 12:21
I have finished my investigation and was not able to find the root cause of this issue.

Re-assigned to 2rec with more market knowledge so we can check it further.

**Comment by tworec** [comment] 2021-06-12 01:17
Upon starting my node (requestor, occasionally connected) I've got
```
[2021-06-12T01:07:55.314+0200 INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:7465" service on 127.0.0.1:7465
[2021-06-12T01:08:24.230+0200 INFO  ya_market::matcher::handlers] Failed to save Offer [5eb3954...].  Error: Offer [5eb395...] expired.
``` 
But on the second node (provider, which is running all the time) this offer was saved (insertion ts witnesses it was just 6s after created on the originating node).
```
select * from market_offer where id like '5eb395%';
           id = 5eb3954fb6694cd5a9a56333ea038723-7f16a68906a257f9d0dfb8112b0fc5659129d6e958a127eb62e2bb2d43cdeb96
   properties = {"golem.activity.caps.transfer.protocol":["gftp","https","http"],"golem.com.payment.debit-notes.accept-timeout?":240,"golem.com.payment.platform.erc20-mainnet-glm.address":"0x8ef6e259de6caca32531e25c14fae71eaee5eef5","golem.com.payment.platform.zksync-mainnet-glm.address":"0x8ef6e259de6caca32531e25c14fae71eaee5eef5","golem.com.pricing.model":"linear","golem.com.pricing.model.linear.coeffs":[0.0,0.000469846835654295,0.0],"golem.com.scheme":"payu","golem.com.scheme.payu.interval_sec":120.0,"golem.com.usage.vector":["golem.usage.duration_sec","golem.usage.cpu_sec"],"golem.inf.cpu.architecture":"x86_64","golem.inf.cpu.capabilities":["sse3","pclmulqdq","monitor","ssse3","fma","cmpxchg16b","sse41","sse42","movbe","popcnt","aesni","xsave","osxsave","avx","f16c","rdrand","fpu","vme","de","pse","tsc","msr","pae","mce","cx8","apic","sep","mtrr","pge","mca","cmov","pat","pse36","clfsh","mmx","fxsr","sse","sse2","htt","fsgsbase","smep","rdtm","rdta","rdseed","rdseed","adx","smap","clflushopt","sha","umip","rdpid"],"golem.inf.cpu.cores":8,"golem.inf.cpu.model":"Stepping 0 Family 23 Model 113","golem.inf.cpu.threads":16,"golem.inf.cpu.vendor":"AuthenticAMD","golem.inf.mem.gib":15.199139714241028,"golem.inf.storage.gib":94.27033364772797,"golem.node.debug.subnet":"public-beta","golem.node.id.name":"l888751qs9qa","golem.runtime.name":"vm","golem.runtime.version":"0.2.0","golem.srv.caps.multi-activity":true}
  constraints = (&
  (golem.srv.comp.expiration>1622697710788)
  (golem.node.debug.subnet=public-beta)
)
      node_id = 0x2a4928aa97958ffcfa823fb8377589e91553e11c
  creation_ts = 2021-06-11 22:06:40.962736641
 insertion_ts = 2021-06-11 22:06:46.928
expiration_ts = 2021-06-11 23:06:40.962736641
```
( Timestamps in DB are in UTC )


The error on my first machine (requestor) was ~104secs after Offer expiration.
The one explanation I see is the unsynchronised clock: my machine vs bcast sender machine, because getting remote offers times out after 3 seconds.

A possible future solution is to cease storing foreign Offers in DB; just have them in the RAM.
For the time being it is of marginal importance, so I'm closing.

Interesting thing is that constraint `golem.srv.comp.expiration>1622697710788` from offer created on 2021-06-11 is pointing `2021-06-03` which means providers are not upgrading constraints after offer is expired and is resubscribed. 
Reported as #1408

**Closed by tworec** 2021-06-12 01:17 UTC
Labels: impact: low, severity: minor

**Comment by tworec** [comment] 2021-06-12 20:12
log message tuned-up via #1401
