### ISSUE TITLE
NET - Include information about having public IP in Offer

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/yagna#1882] opened 2022-03-10 13:13 UTC
Why:
- Requestors could choose Nodes, which can communicate directly (p2p)

What:
- NET endpoint to query information about public IP
- Provider should add this information in his Offer

In case of Requestor logic could change. Reqestor having public IP can choose any Node in the network. Requestor not having it, would like to have Providers with public IP

**Comment by pwalski** [comment] 2022-06-23 08:22
Should implementation of this task include monitoring changes of public IP status?
It would require adding another `ya_provider::Event ` [here](https://github.com/golemfactory/yagna/blob/82825c1270d2deb0f7c98793eff68bf04fbc82a0/agent/provider/src/provider_agent.rs#L430) and some job to send them.

**Comment by pwalski** [comment] 2022-06-24 08:54
Based on discussion:
Ad 1: Public IP should be exposed in Yagna REST API. Provider `Offer`'s property contains only `is_public` boolean flag.
Ad 1: Create new top level REST resource (instead of adding nested resource in e.g. `market`). Most likely something named `net` like.
Ad 3: Yagna should not change `Offer`s properties in order to affect matching (public IP info will be used to do matching).
Ad: 4: If I will not find any better `Offer` property prefix the property key will be `golem.node.is_public`.

**Comment by pwalski** [comment] 2022-06-24 14:22
Regarding REST resource naming:
Create `/net-api/v2`.
Put `ya-net` REST resources to `/net-api/v2/net`.
Resolve name collision caused by `ya-vpn` by moving its resources to `/net-api/v2/vpn/*` (so we will end up among others with `/net-api/v2/vpn/net`).
Update OpenAPI specs https://github.com/golemfactory/ya-client/blob/master/specs

**Closed** 2022-07-06 06:47 UTC
Labels: optional, hybrid-net
